### ISSUE TITLE
unable to boot

### ISSUE THREAD

**Issue by nazirulizzat** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#10]
hi
im using 3020 MT stock I5 3.2GHz
i follow all the instruction given, but no success. the EFI i just change the MAC address and serial id.
the OS i using BigSur and copy using mbp.

![Untitled](https://user-images.githubusercontent.com/76627024/110405210-3288d500-80bb-11eb-8728-5717aabc0d88.jpg)

**Comment by varszegimarcell** [comment]
Hello

It seems like, the CFG Lock is not disabled, at least to my knowlege, this is why the boot stucks at this moment.

Make sure that you've run this command in the modGrubEFI shell. 
   setup_var 0xD9E 0x0 

If disabling CFG Lock doesn't works, to temporarly solve this issue, you should edit your conflig.plist, modify the Kernel > Quirks > AppleCpuPmCfgLock and AppleXcpmCfgLock values. These are boolean values, set them to true. According to the OpenCore documentation, these quirks should be avoided whenever possible. For now, at least it gets you booting.

**Comment by nazirulizzat** [comment]
i had run the command.

![Untitled](https://user-images.githubusercontent.com/76627024/110489395-53d4da00-812a-11eb-907c-84a8895ba656.jpg)

and yet still same result

**Comment by varszegimarcell** [comment]
> 
> 
> i had run the command.
> 
> ![Untitled](https://user-images.githubusercontent.com/76627024/110493482-9d72f400-812d-11eb-8a33-9664bf642a9b.jpg)
> 
> and yet still same result

Hey!

Now at least you're in Darwin! That's a progress, even if you still was unable to boot. Previously, you were stuck in the bootloader. Now you hava a kernel panic, which seems like there's insufficent video memory allocated. 

I think you should repeat the modGrubEFI commands stage of the guide. Run the following commands:
   setup_var 0x263 0x2
   setup_var 0x2 0x1
   setup_var 0x144 0x1
   setup_var 0x15A 0x2
   setup_var 0x146 0x0
   setup_var 0x147 0x0
   reboot
It sholud boot up afterwards. Do you use a dGPU, or just the integrated one?

**Comment by nazirulizzat** [comment]
yeah. i did also. but how to put the command? all the together or 1 by one? eg: setup_var 0x263 0x2 setup_var 0x2 0x1 setup_var 0x144 0x1 setup_var 0x15A 0x2 setup_var 0x146 0x0 setup_var 0x147 0x0 , and enter OR 1 by 1. do u get me? i quite noob. sorry. i try 1 by 1 but still the same

**Comment by varszegimarcell** [comment]
> yeah. i did also. but how to put the command? all the together or 1 by one? eg: setup_var 0x263 0x2 setup_var 0x2 0x1 setup_var 0x144 0x1 setup_var 0x15A 0x2 setup_var 0x146 0x0 setup_var 0x147 0x0 , and enter OR 1 by 1. do u get me? i quite noob. sorry. i try 1 by 1 but still the same
> im using integrated gpu.

No problem mate!

You should run all the commands one by one, and pay special attenion to typeos. If you make a mistake in the command, the shell will become unresponsive, and don’t execute anything unless you reboot the machine into the shell again. 

You can run any of these commands multiple times, it does not do any damage. 

I assume that you’ve followed the OpenCore install media making guide. Did you used the generic OC EFI, or you’ve downloaded mine, and copied that to the disk? Use my EFI please, with the generic OC one, you have to do all the tweaks yourself for a successful boot.

Also, you MUST use the DP output, Mac does not support VGA from mid 2015.

**Comment by varszegimarcell** [comment]
Are you getting a kernel panic?

**Comment by nazirulizzat** [comment]
all done now. i create a new plist using oc gen x.working flawlessly
