### ISSUE TITLE
Display issues after new Update 

### ISSUE THREAD

**Issue by mmfixemer** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#13]
Hey,
One more issue with the display or even the whole system.
The issue I have is after maybe 1 hour (last time even less maybe 30 min) the screen froze and I only heard audio from the video I was watching but nothing else worked. Since then I reverted back to the old version and all is working fine again. Don't know if it's a kext issue or something else.
If you need any more details let me know.

Best regards Mike

**Comment by varszegimarcell** [comment]
Hey!

That's probably a kext related issue, but I hadn't came across this bug yet. 

Thanks for letting me know, if you have any debug information, feel free to share. ;)

**Comment by mmfixemer** [comment]
I have a look today. I will re-up date to the new version and see if I can get a log for the fault. If you could guide me how I can obtain a log for the issues. Thanks in advance

**Comment by varszegimarcell** [comment]
Hey!

Some other guys had the same issue like you encountered, I link the issue for you: https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/issues/14
