### ISSUE TITLE
sff hiddenBIOS

### ISSUE THREAD

**Issue by Kinetik** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#18]
I managed to extract the BIOS. If you still need it for the future, here it is (just search in the txt)
[3020sff hiddenBIOS.txt](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6260417/3020sff.hiddenBIOS.txt)

**Comment by Kinetik** [comment]
I surgest you add this one also:     setup_var 0x264 x03

As described in Whatervergreen's frame buffer patching manual, this setting must be set to MAX
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md


"DVMT Total Gfx Mem", Help: "Select DVMT5.0 Total Graphic Memory size used by the Internal Graphics Device.", QuestionFlags: 0x10, QuestionId: 598, VarStoreId: 2, VarStoreOffset: 0x264, Flags: 0x10, MinMaxData: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
				OneOfOption Option: "128M" Value: 1
				OneOfOption Option: "256M" Value: 2
				OneOfOption Option: "MAX" Value: 3

**Comment by Kinetik** [comment]
running 1080p HiDPI on a 4k monitor, I notice a considerable boost in iGPU performance with this setting. Specially on full transparent windows. it's must have

**Comment by mgrimace** [comment]
> running 1080p HiDPI on a 4k monitor, I notice a considerable boost in iGPU performance with this setting. Specially on full transparent windows. it's must have

Hi, are you getting 4K on an HD4600, from the iGPU (on Big Sur)? @zearp

**Comment by Kinetik** [comment]
Yes

**Comment by Kinetik** [comment]
must have:
DeviceProperties:
(paste this in PropperTree)

<dict>
	<key>AAPL,ig-platform-id</key>
	<data>AwAiDQ==</data>
	<key>device-id</key>
	<data>EgQAAA==</data>
	<key>disable-external-gpu</key>
	<data>AQAAAA==</data>
	<key>disable-hdmi-patches</key>
	<data>AQAAAA==</data>
	<key>framebuffer-fbmem</key>
	<data>AAAAAw==</data>
	<key>framebuffer-patch-enable</key>
	<data>AQAAAA==</data>
	<key>framebuffer-stolenmem</key>
	<data>AAAABA==</data>
	<key>framebuffer-unifiedmem</key>
	<data>AAAAgA==</data>
</dict>
</plist>

and NVRAM boot-args     -igfxmpc -igfxcdc -igfxdvmt

**Comment by varszegimarcell** [comment]
Correct, also 1080p@144Hz works.

**Comment by varszegimarcell** [comment]
> 
> 
> I surgest you add this one also: setup_var 0x264 0x3
> 
> As described in Whatervergreen's frame buffer patching manual, this setting must be set to MAX, by default is at 256M
> https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md
> 
> "DVMT Total Gfx Mem", Help: "Select DVMT5.0 Total Graphic Memory size used by the Internal Graphics Device.", QuestionFlags: 0x10, QuestionId: 598, VarStoreId: 2, VarStoreOffset: 0x264, Flags: 0x10, MinMaxData: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
> OneOfOption Option: "128M" Value: 1
> OneOfOption Option: "256M" Value: 2
> OneOfOption Option: "MAX" Value: 3

I will check it out, probably will be helpful for graphics.
