### ISSUE TITLE
updated SSDT's 

### ISSUE THREAD

**Issue by Kinetik** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#19]
[3020sff_SSDT.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6314059/3020sff_SSDT.zip)

Hi, I grabbed the latest SSDT's samples and went trough the manual mode on Dortania's guide. If you want, check them out

**Comment by varszegimarcell** [comment]
Hey, thank you!

Sorry for not being to active here, I was busy with the uni, as well as I got a new job. Feel free to open a pull request if you made some upgrades to your fork!

**Comment by Kinetik** [comment]
Hi. I was not able to open a pull request. That is why i posted here. Please check the settings

**Comment by varszegimarcell** [comment]
Sorry, I didn't noticed that I have to enable PRs manually! :D

Thanks!
