### ISSUE TITLE
Earthnet cable showing Unpluged  , Internet not working .

### ISSUE THREAD

**Issue by SARVESHTHEPRO** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#20]
Thanks a lot , as you are active , and  helping 
Problem is  internet not  working when using lan cable , first i thought that it problem in cable but after replacing cable everything  and try kext . but  in windows  work fine . So Build new efi form opencore vanilla guide and it works fine but i am unable to fix audio rear port . so can you fix it please. my system is dell op 3020 MT

**Comment by Kinetik** [comment]
Try using the boot-arg alcid=17

**Comment by SARVESHTHEPRO** [comment]
i want to use your efi file . which is showing cable unpluged 
![10 31 58 PM](https://user-images.githubusercontent.com/68787359/115120792-f2c3e000-9fcc-11eb-8ae5-97e1196a7403.jpeg)

**Comment by Kinetik** [comment]
You are confusing me, what about the audio? Did that fix the problem?

**Comment by SARVESHTHEPRO** [comment]
[NO , it  didn't fix audio . now forget about audio] .  I want an answer for how to fix cable unplugged . Which is happning when I am using your given  efi files from github  . In simple i am using your awesome efi files but only the internet is not working while using lan port showing unplugged cable . Sorry for terrible english.  and 

Thanks a lot

**Comment by Kinetik** [comment]
Did you enter your MAC address in the config.plist?

must be entered here:
PlatformInfo->Generic->ROM

**Comment by Kinetik** [comment]
Here is everything you need to fix your issue: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#fixing-en0

Read trough it, find your issue. Good luck!

**Comment by varszegimarcell** [comment]
Hi!

The internal ethernet and audio should work out of the box. Did you checked it on Windows before installing Mac?

**Comment by SARVESHTHEPRO** [comment]
Yes , I have checked in windows and linux it work like a charm .
