### ISSUE TITLE
No picture at install

### ISSUE THREAD

**Issue by smulle48** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#21]
Hi

I'm trying to install on my machine. I see the Darwin boot and then the signal to the monitor disappear.

I have set the correct nvram settings for my case (MT)

My service tag is: DZ2GV02

This is the last thing I see before the signal disappears 

![image](https://user-images.githubusercontent.com/24297824/115111509-06495980-9f81-11eb-8f25-562e2c38f5ea.png)

**Comment by smulle48** [comment]
After a long struggle, I found the answer.

My system got an Intel Core i5-4570 cpu with Intel HD4600. If I changed the AAPL,ig-platform-id to 0x0166000A according to the WhateverGreen guide, I got into Mac Sur but only with 7mb ram for the GPU.

I then found in the top of the guide this:

"At this point, paragraphs 1 and 4 are automated by WhateverGreen and AppleALC. It works in OS X 10.8 and later, and greatly simplifies graphics enabling in macOS."

Meaning. If the GPU is in the "Native supported DevIDs" list, you can simply delete EVERYTHING in the Add block. And I mean EVERYTHING :-) As my Device-ID is 0x412, it's on the Native supported list, so all there are left is an empty Add and Block, nothing else.

Before:
![Skærmbillede 2021-04-18 kl  17 19 58](https://user-images.githubusercontent.com/24297824/115150829-5e0fbf80-a06a-11eb-8454-969735ff1def.png)

After:
![Skærmbillede 2021-04-18 kl  17 20 09](https://user-images.githubusercontent.com/24297824/115150843-6667fa80-a06a-11eb-8c5f-e61b63918c7f.png)

Now when booting, the GPU works 100%, with all ram correctly assigned :-D and no gfx glitches what so ever :-)

**Comment by Kinetik** [comment]
Hi. Did you test 4k output and 144hz display rate without the Framebuffer patching? 
![Xnip2021-04-19_17-39-24](https://user-images.githubusercontent.com/56897038/115268432-eeb9ce80-a142-11eb-8e94-94853695a418.jpg)

**Comment by varszegimarcell** [comment]
Hey!

It is a little bit weird. As I manually definied the device id, it should be working too, regardless of having HD4400, or HD4600. For the HD4400, manually patching the device id is a must, in case of the HD4600, it is optional. In some cases, the HD4600 iGPU can have a different device id, but I'm not sure why, as it does not indicate any difference between two HD4600 iGPUs. The Whatevergreen guide lists 3 device ids associated with the HD4600, and I use the most common one. Seems like you have an iGPU with a different device id than most HD4600 GPUs. 

I think, we have two options here. Option one is that we leave the config.plsit as is now on the repo, and we add a troubleshooting section to the guide, so other people who ecounters this, can remove the iGPU related stuff from the config. The second option is that we remove the iGPU patches from the config, and for HD4400 users, we add a section to the guide.

I prefer option one at the moment, because as far as I know, these patches are needed to have 4K@60Hz or 1080p@144Hz resolutions working. If you have hardware like this, can you please check if the high resolution/refresh rate for me? THX in advance for your feedback.

**Comment by Kinetik** [comment]
![Xnip2021-04-19_19-07-43](https://user-images.githubusercontent.com/56897038/115268621-20cb3080-a143-11eb-9ad9-ef16117ada71.jpg)


Is you do not specify a Framebuffer, the default is taken, as mentioned in the guide:
![Xnip2021-04-19_19-07-43](https://user-images.githubusercontent.com/56897038/115268754-46583a00-a143-11eb-8c55-0b498951ab87.jpg)

Our default is 0x0D220003, in case of HD4600:
![Xnip2021-04-19_19-04-57](https://user-images.githubusercontent.com/56897038/115268818-553eec80-a143-11eb-929b-df164ef608c3.jpg)

if you click the spoiler section you will see what this patch means:
![Xnip2021-04-19_19-02-16](https://user-images.githubusercontent.com/56897038/115268971-85868b00-a143-11eb-90fc-edbf8fd45c8e.jpg)
![Xnip2021-04-19_19-03-38](https://user-images.githubusercontent.com/56897038/115268993-891a1200-a143-11eb-88ba-ad252c2d00f7.jpg)


What we are doing under DevicePropreties is altering the basic config of Framebuffer 0x0D220003, to output more that is specifies in Apple's drivers. thus enabling 4k output, higher refersh rates etc.

**Comment by smulle48** [comment]
> 
> 
> **If you do not specify a Framebuffer, the default is taken, as mentioned in the guide:**
> 
> ![Xnip2021-04-19_19-07-43](https://user-images.githubusercontent.com/56897038/115268754-46583a00-a143-11eb-8c55-0b498951ab87.jpg)
> 
> 
> 
> **Our default is 0x0D220003, in case of HD4600:**
> 
> ![Xnip2021-04-19_19-04-57](https://user-images.githubusercontent.com/56897038/115268818-553eec80-a143-11eb-929b-df164ef608c3.jpg)
> 
> 
> 
> **if you click the spoiler section you will see what this patch means:**
> 
> ![Xnip2021-04-19_19-02-16](https://user-images.githubusercontent.com/56897038/115268971-85868b00-a143-11eb-90fc-edbf8fd45c8e.jpg)
> 
> ![Xnip2021-04-19_19-03-38](https://user-images.githubusercontent.com/56897038/115268993-891a1200-a143-11eb-88ba-ad252c2d00f7.jpg)
> 
> 
> 
> 
> 
> **What we are doing under DevicePropreties is altering the basic config of Framebuffer 0x0D220003, to output more that is specifies in Apple's drivers. thus enabling 4k output, higher refersh rates etc.**
> 
> 

Fake device id is only for mobile hd4600. Not for desktop hd4600 :-)

**Comment by smulle48** [comment]
> Hey!
> 
> 
> 
> It is a little bit weird. As I manually definied the device id, it should be working too, regardless of having HD4400, or HD4600. For the HD4400, manually patching the device id is a must, in case of the HD4600, it is optional. In some cases, the HD4600 iGPU can have a different device id, but I'm not sure why, as it does not indicate any difference between two HD4600 iGPUs. The Whatevergreen guide lists 3 device ids associated with the HD4600, and I use the most common one. Seems like you have an iGPU with a different device id than most HD4600 GPUs. 
> 
> 
> 
> I think, we have two options here. Option one is that we leave the config.plsit as is now on the repo, and we add a troubleshooting section to the guide, so other people who ecounters this, can remove the iGPU related stuff from the config. The second option is that we remove the iGPU patches from the config, and for HD4400 users, we add a section to the guide.
> 
> 
> 
> I prefer option one at the moment, because as far as I know, these patches are needed to have 4K@60Hz or 1080p@144Hz resolutions working. If you have hardware like this, can you please check if the high resolution/refresh rate is working for me? THX in advance for your feedback. 

Right now I'm connected to our tv so this is the max I can set it to
![image](https://user-images.githubusercontent.com/24297824/115272169-646f6b80-a13e-11eb-96a7-e4ca902508bc.jpeg)

I just tested playing 4K on YouTube without any problem :-)
![image](https://user-images.githubusercontent.com/24297824/115272251-7c46ef80-a13e-11eb-91b4-4a6d064cd61f.jpeg)
![image](https://user-images.githubusercontent.com/24297824/115272285-84069400-a13e-11eb-8c6d-85d8596eb0ef.jpeg)

I don't really need any wild resolution. Just need it to work :-) later I can try to tweak it. Just thought this would be the most easy for n00b's like me, and then later tweaking when I'm comfortable with the system :-)

**Comment by varszegimarcell** [comment]
> 
> 
> > **If you do not specify a Framebuffer, the default is taken, as mentioned in the guide:**
> > ![Xnip2021-04-19_19-07-43](https://user-images.githubusercontent.com/56897038/115268754-46583a00-a143-11eb-8c55-0b498951ab87.jpg)
> > **Our default is 0x0D220003, in case of HD4600:**
> > ![Xnip2021-04-19_19-04-57](https://user-images.githubusercontent.com/56897038/115268818-553eec80-a143-11eb-929b-df164ef608c3.jpg)
> > **if you click the spoiler section you will see what this patch means:**
> > ![Xnip2021-04-19_19-02-16](https://user-images.githubusercontent.com/56897038/115268971-85868b00-a143-11eb-90fc-edbf8fd45c8e.jpg)
> > ![Xnip2021-04-19_19-03-38](https://user-images.githubusercontent.com/56897038/115268993-891a1200-a143-11eb-88ba-ad252c2d00f7.jpg)
> > **What we are doing under DevicePropreties is altering the basic config of Framebuffer 0x0D220003, to output more that is specifies in Apple's drivers. thus enabling 4k output, higher refersh rates etc.**
> 
> Fake device id is only for mobile hd4600. Not for desktop hd4600 :-)

Yes you're right. But a fake ID shouldn't affect anything if you have a real HD4600 with the same ID as you have faked it. It can cause only issues if you have a HD4600 that has a different device ID. I don't know why Intel differentiated the same GPUs with different device IDs, but I have to do more research on the topic. Thank you for letting us know about this issue!

**Comment by varszegimarcell** [comment]
> 
> 
> > Hey!
> > It is a little bit weird. As I manually definied the device id, it should be working too, regardless of having HD4400, or HD4600. For the HD4400, manually patching the device id is a must, in case of the HD4600, it is optional. In some cases, the HD4600 iGPU can have a different device id, but I'm not sure why, as it does not indicate any difference between two HD4600 iGPUs. The Whatevergreen guide lists 3 device ids associated with the HD4600, and I use the most common one. Seems like you have an iGPU with a different device id than most HD4600 GPUs.
> > I think, we have two options here. Option one is that we leave the config.plsit as is now on the repo, and we add a troubleshooting section to the guide, so other people who ecounters this, can remove the iGPU related stuff from the config. The second option is that we remove the iGPU patches from the config, and for HD4400 users, we add a section to the guide.
> > I prefer option one at the moment, because as far as I know, these patches are needed to have 4K@60Hz or 1080p@144Hz resolutions working. If you have hardware like this, can you please check if the high resolution/refresh rate is working for me? THX in advance for your feedback.
> 
> Right now I'm connected to our tv so this is the max I can set it to
> ![image](https://user-images.githubusercontent.com/24297824/115272169-646f6b80-a13e-11eb-96a7-e4ca902508bc.jpeg)
> 
> I just tested playing 4K on YouTube without any problem :-)
> ![image](https://user-images.githubusercontent.com/24297824/115272251-7c46ef80-a13e-11eb-91b4-4a6d064cd61f.jpeg)
> ![image](https://user-images.githubusercontent.com/24297824/115272285-84069400-a13e-11eb-8c6d-85d8596eb0ef.jpeg)
> 
> I don't really need any wild resolution. Just need it to work :-) later I can try to tweak it. Just thought this would be the most easy for n00b's like me, and then later tweaking when I'm comfortable with the system :

> 
> 
> > Hey!
> > It is a little bit weird. As I manually definied the device id, it should be working too, regardless of having HD4400, or HD4600. For the HD4400, manually patching the device id is a must, in case of the HD4600, it is optional. In some cases, the HD4600 iGPU can have a different device id, but I'm not sure why, as it does not indicate any difference between two HD4600 iGPUs. The Whatevergreen guide lists 3 device ids associated with the HD4600, and I use the most common one. Seems like you have an iGPU with a different device id than most HD4600 GPUs.
> > I think, we have two options here. Option one is that we leave the config.plsit as is now on the repo, and we add a troubleshooting section to the guide, so other people who ecounters this, can remove the iGPU related stuff from the config. The second option is that we remove the iGPU patches from the config, and for HD4400 users, we add a section to the guide.
> > I prefer option one at the moment, because as far as I know, these patches are needed to have 4K@60Hz or 1080p@144Hz resolutions working. If you have hardware like this, can you please check if the high resolution/refresh rate is working for me? THX in advance for your feedback.
> 
> Right now I'm connected to our tv so this is the max I can set it to
> ![image](https://user-images.githubusercontent.com/24297824/115272169-646f6b80-a13e-11eb-96a7-e4ca902508bc.jpeg)
> 
> I just tested playing 4K on YouTube without any problem :-)
> ![image](https://user-images.githubusercontent.com/24297824/115272251-7c46ef80-a13e-11eb-91b4-4a6d064cd61f.jpeg)
> ![image](https://user-images.githubusercontent.com/24297824/115272285-84069400-a13e-11eb-8c6d-85d8596eb0ef.jpeg)
> 
> I don't really need any wild resolution. Just need it to work :-) later I can try to tweak it. Just thought this would be the most easy for n00b's like me, and then later tweaking when I'm comfortable with the system :-)

Can you check it in the diplays OSD that it really runs at 120Hz? 

I will think about updating the guide (and maybe even the config) to address this issue like you ecountered. :D

**Comment by Kinetik** [comment]
p.s. playing a 4k video on YouTube is not the same as outputting 4k from iGPU

**Comment by smulle48** [comment]
> Yes, it's true, you don't need the device-id for the desktop igpu, but you need the framebuffer-patch. I removed now the device-id, no change. If I remove the AAPL, whatever green faults at boot. 

I just tried to add it all again to my usb stick leaving the hdd efi untouched. When booting from the usb stick I'll end up with "no picture" but the hdd efi boot up without any problem.

Does the settings make the system boot up with max settings? Maybe my tv (and maybe also others monitor) can't handle the resolution and that's why I don't get any picture

**Comment by Kinetik** [comment]
do you use a DP to HDMI cable?

**Comment by smulle48** [comment]
> do you use a DP to HDMI cable?

Yes. Unfortunately does my tv not have an dp port

**Comment by Kinetik** [comment]
I have one of these laying around. I will test the output on the monitor. The reason I am not using it, at all, it's because it's a 10eur cable and it cannot output more that 4k 30hz. More expensive cables can run at 4k 60hz (20-30eur). This was on windows, I'm going to test on the macos soon
This is a nice test case, because I suspect there could be more people installing, witch do not have monitors with a DP

**Comment by Kinetik** [comment]
I found out what is needed for a DP to HDMI cable setup. It was normal that you got a black screen.

https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#lspcon-driver-support-to-enable-displayport-to-hdmi-20-output-on-igpu

I will test soon and setup this port connection driver support. But still i think i would prefer to set up the ports and pipes myself manually in Device Properties. Will see

**Comment by Kinetik** [comment]
like described here: https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html

**Comment by Kinetik** [comment]
As you already have the setup, to make things a bit faster, can you please help me with a test. Can you please put back the DeviceProperties in your config and add this boot-arg to nvram:-igfxlspcon

**Comment by Kinetik** [comment]
For those interested on the subject, this is one link to bookmark and study: https://osxlatitude.com/forums/topic/8723-enabling-dvidphdmi-and-increasing-vram-with-intel-haswell4th-gen-hd420044004600etc-igpu/

**Comment by varszegimarcell** [comment]
I will update the guide according to this issue. 

I decided that we'll not fake any GPU IDs in the config, but we will leave all graphics patches in place. That will make graphics work properly on every HD4600 GPUs, regardless its specific Hardware ID. However, if anybody would use the HD4400, I will add a section in the guide discussing this topic, so you can add the fake HD4600 device ID by yourself. 

I think that would be the best solution, what do you think about it?

**Comment by grochib** [comment]
> @varszegimarcell :-D
> 
> After a long struggle, I found the answer.
> 
> My system got an Intel Core i5-4570 cpu with Intel HD4600. If I changed the AAPL,ig-platform-id to 0x0166000A according to the WhateverGreen guide, I got into Big Sur but only with 7mb ram for the GPU.
> 
> I then found in the top of the guide this:
> 
> "At this point, paragraphs 1 and 4 are automated by WhateverGreen and AppleALC. It works in OS X 10.8 and later, and greatly simplifies graphics enabling in macOS."
> 
> Meaning. If the GPU is in the "Native supported DevIDs" list, you can simply delete EVERYTHING in the Add block. And I mean EVERYTHING :-) As my Device-ID is 0x412, it's on the Native supported list, so all there are left is an empty Add and Block, nothing else.
> 
> Before: ![Skærmbillede 2021-04-18 kl 17 19 58](https://user-images.githubusercontent.com/24297824/115150829-5e0fbf80-a06a-11eb-8454-969735ff1def.png)
> 
> After: ![Skærmbillede 2021-04-18 kl 17 20 09](https://user-images.githubusercontent.com/24297824/115150843-6667fa80-a06a-11eb-8c5f-e61b63918c7f.png)
> 
> Now when booting, the GPU works 100%, with all ram correctly assigned :-D and no gfx glitches what so ever :-)

I must thank the author so much! This helped me after such a long struggle to find the solution! 

Thanks a million times!

**Comment by grochib** [comment]
> @varszegimarcell :-D
> 
> After a long struggle, I found the answer.
> 
> My system got an Intel Core i5-4570 cpu with Intel HD4600. If I changed the AAPL,ig-platform-id to 0x0166000A according to the WhateverGreen guide, I got into Big Sur but only with 7mb ram for the GPU.
> 
> I then found in the top of the guide this:
> 
> "At this point, paragraphs 1 and 4 are automated by WhateverGreen and AppleALC. It works in OS X 10.8 and later, and greatly simplifies graphics enabling in macOS."
> 
> Meaning. If the GPU is in the "Native supported DevIDs" list, you can simply delete EVERYTHING in the Add block. And I mean EVERYTHING :-) As my Device-ID is 0x412, it's on the Native supported list, so all there are left is an empty Add and Block, nothing else.
> 
> Before: ![Skærmbillede 2021-04-18 kl 17 19 58](https://user-images.githubusercontent.com/24297824/115150829-5e0fbf80-a06a-11eb-8454-969735ff1def.png)
> 
> After: ![Skærmbillede 2021-04-18 kl 17 20 09](https://user-images.githubusercontent.com/24297824/115150843-6667fa80-a06a-11eb-8c5f-e61b63918c7f.png)
> 
> Now when booting, the GPU works 100%, with all ram correctly assigned :-D and no gfx glitches what so ever :-)

Hey smulle48, 

I was wondering if you have the same issue: in my Display settings there is no choice of an AirPlay Display (in the lower left). Is this the same for you too?

Please get back to me as I also just deleted the entry from the config.plist and Monterey started without any other issue.

Thanks a lot again!

Best

grochi
