### ISSUE TITLE
Intel Wireless card? Lenovo Intel 7260NGW Wireless-AC 7260 Laptop WiFi BlueTooth Combo Card 04X6087

### ISSUE THREAD

**Issue by tylermmoore** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#26]
Hey got things mostly working but trying to add this wireless card. I added https://github.com/OpenIntelWireless/itlwm this kext to the folder then ctrl +R in Propertree to add it to the config. Looks like its in the plist file but maybe not loading when the OS boots up. Has anyone had experience with this one?  Do i need to clear the Nvram?

**Comment by varszegimarcell** [comment]
Hi!

Maybe an nvram clean helps, but I would recommend to rebuild the kextcache with this command:

    sudo kextcache -i /

Also, you can check what kexts are loaded with the command:

    kextstat

I would filter it's output with grep like this:

   kextstat | grep itlwm
   
If it loaded and still doesn't works, than I have no idea, presonally I never used this kext. It is a pretty experimental project AFAIK. 

M

**Comment by varszegimarcell** [comment]
Also, dont forget to reboot after you've rebuilt the kextcache.

**Comment by tylermmoore** [comment]
Hi, Thanks for the help, Looks like clearing the nvram did work. Ill do some testing and let you know how it works.

**Comment by tylermmoore** [comment]
Wifi looks to be working with decent speed. I need to get some antennas and play around with it a bit. Thanks for the help
