### ISSUE TITLE
Problems with 3020 SFF sleep, power configuration, and wifi icon in menu bar

### ISSUE THREAD

**Issue by Oxford999** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#28]
Running Big Sur with your files. The machine is a SFF model with an i5 and the 4600 graphics. Each time I made changes with grub commands, following your guide, I was told there is a mismatch ("not expected" or something). Each time it said it was successful, though. (If this is normal behavior please say that in the guide because it's not very comforting to get those messages, especially given the concern over "bricking" the machine. Also, the guide says resetting NVRAM with OpenCore won't change the values but doesn't indicate why one would want to reset the NVRAM with OpenCore. Is that necessary to do at some point?) Are the mismatches because my machine has an i5 and yours has an i3? I wonder if those mismatches have something to do with the following problems:

Although Wi-Fi doesn't show up in the System Preferences' Network screen, the icon always appears in the desktop menu bar. It always animates and switches to blue, indicating that it's on. No networks show up, though. I can't find a way to remove the Wi-Fi icon or to stop this animation/turn on behavior.

Although I'm not 100% sure, I think the Ethernet is also not working. The Ethernet does show up in System Preferences but when I plug a cable in it continues to say it's unplugged. I am going to check with a different cable into a different router to be certain but since the router I plugged into is the one used to broadcast Wi-Fi at my friend's home, I assume it should be outputting via its ethernet ports, too.

A poster on another site said their 3020 has a Realtek ethernet chip but Dell's site says the 3020 SFF has an Intel 10/100/1000 chip. So, I assume that other 3020 is a different model. I am wondering if I need to install an Intel ethernet kext, like IntelMausi. But, since you have the SFF model I would think yours also has the Intel networking so I shouldn't have to do anything.

Also, OpenCore 0.6.8 is out, although I'm not sure we're missing much by sticking with the 0.6.7 files you're using here.

Thanks very much for the effort you have put into this project!

**_Edit: Edited title to reflect what the actual problems are, as ethernet has been working from the start._**

**Comment by Kinetik** [comment]
I am running also on a 3020 SFF with a i5 and HD4600 and I have not encountered any issue. Have you installed windows previously and network was working? Did you update BIOS to version A20?

**Comment by Oxford999** [comment]
Hello. The machine is a certified refurb from MicroCenter that I just purchased. Here are the specs:

Intel Core i5 4570 3.2GHz Processor
16GB DDR3-1600 RAM _CL11, so slow but it works_
512GB SSD. _Kingfast QLC -- so slow and very low-end but it works_
Intel HD Graphics 4600
Windows 10 Pro _not anymore_
DVD-ROM Drive. _CD reading is working. Have not tested DVD playing._
MSI Optix G32C4 monitor _connected with an '8k' displayport cable. Audio out is also connected and working._

The ethernet is actually working. The wifi router I tried to connect to at my friend's (the machine is for her) wouldn't work but I went home and got a long cable and connected directly to her cable modem. So, ethernet isn't an issue. I wasn't 100% sure it was broken before and it turns out there is something weird about the wifi router she has attached to the cable modem. In any case, it's fine going directly from the cable modem so ethernet is solved. (I don't know why Intel's site claims these machines have Intel 10/100/1000 nics in them when they're Realtek. The program 'Hackintool' reported that it's a Realtek and it's now working.)

The strange behavior of the wifi icon in the menu bar at the top right area of the Mac desktop, though, remains unsolved.

Worse yet, I am having the same problem with sleep that one of the people responding to your Reddit post reported. When attempting to wake the machine I get an off-colored Apple logo and have to hold the power button down to shut off the machine. I tried to go through the complex Dortania guide/troubleshooting and, based on the 'Fixing/optimizing power management' part of the guide, the machine's OpenCore configuration isn't configured in terms of enabling functioning power management. The name of the broken sample in the Dortania guide image shows 'cpu0' and the functioning one shows 'cpu00'. Mine shows 'cpu' and very little happening. According to the guide the configuration is 'missing XCPM'.

Sleep seemed to be working initially, in that the machine would awaken properly if put to sleep and awakened relatively soon after. What I then noticed is that if it has been asleep for quite some time that's when the off-color logo would appear, including any time the machine put itself to sleep. After setting the machine up for my friend I found that the off-color logo problem began to appear even if I would put the machine to sleep and awaken it soon after. I had swapped the generic (AST) keyboard for her old Mac Pro keyboard (from an ancient G4 Mac) in the hopes that the generic keyboard was causing issues with sleep. The machine always claimed there is 'no keyboard' at boot and swapping for the Mac keyboard did stop that. Regardless of the newly-worsened sleep behavior, the machine is unusable for her if it crashes if left asleep for a while anyway. So, I'm trying to follow all the complexity about USB and power management in the Dortania guide. It's a bit overwhelming. Since the grub commands in your guide caused the OS to complain when I entered each of them I don't know if that broke power management somehow. I think the guide mentions something about how various power management speed settings are based on the multiplier/speed of the CPU. So, perhaps since you had a different CPU when you made the configuration that is causing an issue.

![IORegistry_results](https://user-images.githubusercontent.com/83545492/116906977-f5e6df00-ac0e-11eb-9a11-a1addc8bcd70.png)

The Dortania guide says incorrect USB mapping is the biggest cause of sleep problems but it refers to the readme file for the USBMap project for information and there is practically no information in that readme. The project manager said he/she is trying to find time to write a readme. So, I'm trying to figure out why the Dortania guide says it has all the needed info in it when it doesn't — and also how to fix the USB configuration if it needs to be fixed.

![USB_guide1](https://user-images.githubusercontent.com/83545492/116907862-2d09c000-ac10-11eb-9202-98cfd0c44a9b.png)

from the 'outdated' guide:
![USB_guide2](https://user-images.githubusercontent.com/83545492/116907869-2f6c1a00-ac10-11eb-9ea0-e5fe78ff33f9.png)

Also, I believe I read something on your Reddit page (or perhaps elsewhere) about clearing out all the entries for the 4600 in the OpenCore configuration in order to get above 1080 resolution. Apparently, the reason the entries are there is for 4400 chips to work. The monitor she's using is 1080 and the high refresh settings work (up to 165 Hz but I have it set at 120 Hz because that seems to give crisper text and she doesn't play video games). Do I need to remove any entries about the 4600? I assume the answer is no since your machine has the same GPU.

Thanks again for any help you can provide.

**Comment by Oxford999** [comment]
BIOS is A20.

**Comment by Oxford999** [comment]
Here is the report someone else made of the same problem I'm having with sleep:

![sleep_problem](https://user-images.githubusercontent.com/83545492/116909298-0482c580-ac12-11eb-9e22-a8e8f24e44a0.png)

I am _trying_ to follow the Dortania guide as suggested. I got this particular machine from MicroCenter for my friend because I thought, since it has identical hardware, it would make it much simpler to get it working.

**Comment by Kinetik** [comment]
Have a little more patience. If you check the Pull Requests section of this repository you will see my PR witch has included all these improvements that you are looking for. I went trough all the ACPI and USB mappings and recreated them, in the manual - hard - preferred way. I even extracted the bios to search for missing potential settings (found one). There are three major improvements into one PR. They are being tested now by the owner and I suspect they will be implemented soon. Sleep will be fixed and many more power hiccups.

**Comment by Oxford999** [comment]
I am patient but the woman I am helping is expecting me to get this done. I have been at her house for two days already and have been put behind in my other work, much of which is time-sensitive. The guide here says the machine is fully working when one gets to the end of it so that should be taken out and replaced with caveats. Thanks again for the reply. I will take a look at what you submitted.

![fully_functional](https://user-images.githubusercontent.com/83545492/116910253-5a0ba200-ac13-11eb-866a-6486ce6afc53.png)

**Comment by Oxford999** [comment]
I am looked at the pull requests and don't know how to use that information. I am new to this system so I have another thing to learn. All I can understand at this point is that the originator of this project knew that a better USB mapping solution was possible, didn't choose to do it that way, and didn't mention any of that in the guide — even though the Dortania guide says incorrect USB mapping is not only the main source of sleep problems, it can also lead to data corruption. And, I also gather than your USB mapping improvements, which appear to be critical for getting sleep to work, haven't been merged with the main files. The project's originator seems to now say he/she is too busy to continue to do things with it. So, I hope I can figure out how to manually use the changes you provided.

**Comment by Oxford999** [comment]
I _think_ I am on the right track what I'm supposed to do with your changes. However, when I ran USBMap to get a kext for it (since I didn't find one to download from here) the results were different from your plist file. For instance, in yours:

			<key>CFBundleIdentifier</key>
			<string>com.apple.driver.AppleUSBMergeNub</string>
			<key>IOClass</key>
			<string>AppleUSBMergeNub</string>
			<key>IOPathMatch</key>
			<string>IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC@14/XHC@14000000</string>
			<key>IOProviderClass</key>
			<string>AppleUSBXHCIPCI</string>
			<key>IOProviderMergeProperties</key>
			<dict>
				<key>kUSBMuxEnabled</key>

But in the one generated by the program:

			<key>CFBundleIdentifier</key>
			<string>com.apple.driver.AppleUSBHostMergeProperties</string>
			<key>IOClass</key>
			<string>AppleUSBHostMergeProperties</string>
			<key>IOParentMatch</key>
			<dict>
				<key>IOPropertyMatch</key>
				<dict>
					<key>pcidebug</key>
					<string>0:20:0</string>
				</dict>
			</dict>
			<key>IOProviderClass</key>
			<string>AppleUSBXHCIPCI</string>
			<key>IOProviderMergeProperties</key>
			<dict>
				<key>kUSBMuxEnabled</key>

I don't know if I should use your plist or the one the program generated. I am nervous about losing USB by doing the wrong thing. Since there was no readme with USBMap I wasn't sure if I needed to do anything beyond discovering the ports and then building the kext. The Dortania guide talked about plugging things in but I didn't see anything in the USBMap interface telling me to do that. Can I just run USBMap, discover the ports, build the kext, and that's it? (Other than deleting the obsolete USB mapper and its info file and modifying the main config.plist for OpenCore.) Will the machine work with the plist USBMap generates or do I need to substitute yours? Do I need to add in anything to the EFI folder? 

I'm trying to figure out why AppleACPIPlatformExpert shows up in your plist and not in the one generated by USBMap. I also have _some_ ports that are labeled #port with the USBMap plist I generated but in yours they're all labeled with UsbConnector. That indicates to me that something may not be finished with the plist I generated. Also, there is a USB 1 hub in the keyboard I'm using which adds two more ports. I am under any 15 port limit, though. USBMap lists all the ports detected as being USB 3, even though the machine only has two USB 3 ports.

**Comment by Kinetik** [comment]
If you look into the PR at changed files, you can download the USBMap.kext I've put there, or you can ask for it. 
[USBMap.kext.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6417058/USBMap.kext.zip)

**Comment by Kinetik** [comment]
Did you find a working serial number and entered the MAC address into the plist?

**Comment by Oxford999** [comment]
Thank you for the kext. I did look at the PR several times but only saw plists and changes. I am new to github. 

Yes to both questions. I followed the guide here.

Do you have any idea why the USBMap kext I generated lacks the AppleACPIPlatformExpert entry yours has? And, also, yours has com.apple.driver.AppleUSBMergeNub but the other one has com.apple.driver.AppleUSBHostMergeProperties.

I am wondering if something has changed with USBMap. Since there doesn't seem to be documentation (I assume there was for an older version, based on the Dortania guide telling people to read its readme) I'm under the impression that the program has changed quite a bit.

**Comment by Kinetik** [comment]
I used the latest sample for the kext. If you used one generated by a program, could be old or could be Clover requirements.

**Comment by Oxford999** [comment]
I got USBMap from the repository via the link in the Dortania guide. It should be the most recent.

Since the guide says its section on USBMap is out of date I would assume the sample you used is also old. But, if it works that's the main thing. I wonder if I need to stop using the Apple keyboard, though, because it adds two more USB ports than what I assume your configuration uses. Does adding a USB hub require a person to use USBMap again to add the additional ports?

**Comment by Kinetik** [comment]
No, you assume wrong. The guide instructions and the sample file from the repository are not the same thing. I fail to understand your issues, your are having multiple...or none. I don't know. Good luck

**Comment by Kinetik** [comment]
Please don't forget to close the issue when done

**Comment by Oxford999** [comment]
My issues are:

1. The wifi icon appears at boot even though there is no wireless in the system. I don't know how to remove it. It appears to turn wifi on but there are no networks detected.

2. Sleep does not work. This appears to be because USB is not mapped correctly and power management is not set up correctly. Both problems are due to this guide not being done correctly, even though it claims that a person following it will have a fully-functional machine when they follow it.

The sleep problem's symptoms are exactly the same as the person from Reddit, whose post I showed in a screenshot.

**Comment by Caibuk** [comment]
Your posts could be perceived as quite rude and offensive. I suspect, you won't get any more help here.
You paid for nothing and still insist someone owes you "a fully-functional machine".
I propose you buy an actual Macintosh. Then you have someone to blame.
Good luck as well.

**Comment by Oxford999** [comment]
The old woman on a very tight budget I was helping can't afford to buy a real Mac again. Hers would work for her if not for Apple abusing security update availability to force people to give up otherwise fully-working equipment. So, yes... buying a real Mac happened and some of the blame rests with Apple.

I have been helping her because I am a charitable person. It is now going to cost me $320 in parts (plus all my time, including the drive to MicroCenter). This is because when I claim something is fully-functional **I choose to stand by it**. I have had to take back the machine and eat the cost, since she threw away the boxes.

Instead of worrying about my personality perhaps you can get the files and guide here in better shape, so others won't be taken by the broken promise of a fully-working configuration. This is not the first Hackintosh project for me. I successfully set up a netbook with 10.6.8 for that same lady and it worked, including sleep. That is not the only one I got working. The difference, it seems, is that the guides I followed were reliable.

It is not too much to ask for a guide to represent itself properly. If the person who created it doesn't understand how things like USBMap work (something indicated in a comment in response to the PR) and have chosen to take the 'lazy' route (his word choice, not mine) then the guide should not promise full functionality. It should have specified that there are better, more robust, methods that were not used.

I know from experience that sleep issues are a major problem with Hackintosh. Had there been clarity in the guide about its unreliability I would have never spent the money, time, and reputation on the OptiPlex with OpenCore and the files/guide here. It seemed obvious to me that fully-working and fully-functional means sleep is working, power management is configured correctly, and USB is mapped according to the best practices specified by the Dortania guide — the very guide the creator of this guide and files pointed someone to many days ago when he/she reported the same problem with sleep.

Expecting various minor glitches is fine (and normal for Hackintosh) but finding that sleep crashes the machine is such a serious problem that it has no business being called fully functional. Not using USBMap and relying on USBInjectAll instead, even though someone else reported the same sleep problem and the Dortania guide and other sources say USBInjectAll should only be used temporarily at most — that is the sort of critical information that there is simply no excuse to not present to readers.

What is rude is belittling people when they ask for help, like claiming they're too impatient — when this repo has been around for months and has its own github section. If anyone doesn't want to help that's up to them. What they're not entitled to do is insult people because they're having problems, including when they point out that a guide that promises full functionality should either provide it or not claim to provide it.

**Comment by Kinetik** [comment]
First of all this repo is being used by many people witch do not share your issues. If you are not willing to go trough the entire Dortania's guide to create your own, well @varszegimarcell dit it for us, but he probably made some mistakes, he is not a machine or company. We few witch are passionate, are willing to help him improve it by **reading again all manuals** and trying to correct or improve. The USBMap is one of them , witch **I was willing** to go trough and add it. It is the current PR witch will be in part of the next release soon. 

The wifi icon appears even if you don't have a wifi card installed (default for iMac). You can disable it from System Preferences -> Dock & Menu Bar->Wifi->Show in menu bar.  This is a macOS setting, nothing to do with OC

<img width="663" alt="image" src="https://user-images.githubusercontent.com/56897038/117170843-06e04d80-add3-11eb-804d-933998cffbe6.png">

**Comment by Kinetik** [comment]
And a final word on the matter as the owner will never say it, because we are both gentelmen :). Please forgive us for putting a large ammount of hours to get it up and running more and more correctly, but failed to specify the correct state word in the guide. Functional not working. We will change it soon into "k**s our *ss" . Cheers

**Comment by Kinetik** [comment]
I think you should just close this issue. I don't think we will hear from him again. 
This is a perfectly good example of how NOT to behave in this community. Taking people for granted and arguing a 10 page long comment, of how he is pissed that this is not perfect and his time is waisted. 

You should mention in the disclaimer that any support will be given only for personal projects, as is the OpenCore project. This is not anything plug-n-play like, that updates it's self. It's a long term personal project for witch some time and interest must be invested into, in order to benefit from the correct functionality.
