### ISSUE TITLE
Suggestions for guide rewrite and cleanup

### ISSUE THREAD

**Issue by varszegimarcell** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#29]
Hi!

I want a make major rewrite to the guide, which will make this repo more easy to use, and much more clear. 

But I need your suggestions to be really effective here. If you have any recommendations, or you've found any mistakes, let me know here in this issue, and hopefully we can make the guide better together.

Cheers
M

**Comment by Kinetik** [comment]
Unfortunately, guides are not my strong suit 😊. As personal preference, I would like it as simplistic as possible for the initial install and steps. Then, in-depth options and troubleshooting. 
In my opinion, if you are providing a "good to go" EFI, then the parts about the standard peripherals used, bios commands, SMBIOS and after install steps, should be simple to follow without too many parentheses (). It is already well composed, maybe just a few changes, I will think about it

**Comment by Xtendera** [comment]
Hey Kinetik, I agree. But no matter how good the guide your following is, there will always be some issue. This is especially true because of HD 4400 CPUs. I know it sucks, it would be cool to make a perfect guide too, but you will know that it is not possible when you look at the word "Hackintosh". **Hack**intosh. I am ready to help both of you make this as good as possible, but in my opinion, it better to have a Troubleshooting section with your problem already written than for you to have to create an issue, wait for an answer, and then get a possible solution.  Most of the issues are repeating anyways. You know, _Didn't disable CFG Lock, Black Screen because of device-id,_ that kind of thing.

**Comment by Kinetik** [comment]
One cleanup suggestion I would ask you to close all open "old" issues that have been resolved in time with new releases.

**Comment by Kinetik** [comment]
I also agree with a troubleshooting area, but for actual troubles. Not disabling CFG Lock, means that someone did not go trough the guide correctly. Probably got anxious and did not read till the end, or skipped. Sorry but that to me sounds like making a noob version of the install wiki to witch I do not agree and should not be supported in my opinion. 

And the device-id needs to be there in my opinion, I am still not convinced that this is the solution, as everywhere I read, It sais it needs to be there for the 4400. I still say it's because of the DP to HDMI cable and 4k monitor issue. But I leave it to others to figure this one out because I think we should not support any connection other than display ports.

Like I said, make the troubleshooting yes, but for actual troubles. These do not qualify in my opinion.

**Comment by Kinetik** [comment]
I would start using the Wiki section for extra documentations that will have links in the main page. What do you think about that?

**Comment by varszegimarcell** [comment]
> I would start using the Wiki section for documentations and install steps/versions that will have links in the main page. What do you think about that?
> 
> There you hame more space for organising and can follow easier with the page bar on the right.

Wow, that’s a great idea!

The readme.md than could contain relevant information about current issues, bugs, and changes. 

At the moment, I do not know how can I write a wiki page, but in the afternoon, I’ll read after that.

**Comment by Kinetik** [comment]
I already transferred most of the content to wiki pages. You just need to remove those entire sections from the readme.md and replace them with links to those pages

This is a first step in my opinion. Next, the information in the pages needs revision, I would transfer all personal notes to a separate page and keep everything more technical, but that's just me 🙃. Also the order of the pages, I think, needs to be changed

**Comment by Kinetik** [comment]
Here is my idea for the readme.md (below). The Installation wiki part, each line should be a link to a separate wiki page:


This repository contains a guide on how to install macOS on the Dell Optiplex 3020 series, with the necessary files, using OpenCore bootloader.

This guide covers the following macOS versions:

macOS 11 Big Sur

This Optiplex series is one of the pre-built desktops from DELL, witch has a very good match to one of apple SMBIOS’s. That is the iMac 15,1. A SMBIOS I basically a package of drivers and settings, that are being setup during macOS installation. 
https://everymac.com/systems/apple/imac/specs/imac-core-i5-3.3-27-inch-aluminum-retina-5k-mid-2015-specs.html#macspecs1

This guide supports only personal projects. Meaning we do not support any issues if you are installing this for someone else. 

For installation you must remove any extra hardware installed. (Ex. PCIe Lan or Wifi cards, Graphics cards). If you install this EFI with additional hardware installed it will not work correctly, or at all.


3020 Standard Hardware List

Motherboard: Dell CBX3
CPU’s: Intel Series 4000 Haswell H81
GPU’s integrated: HD4400 or HD4600
Display out type: DisplayPort 
Network Card: Realtek RTL8111
Hdd: SSD (optional but optimal)
RAM: DDR3 1600mhz


Installation wiki:
This setup describes the setup for the SFF version of the series. For M and MT specifics will be mentioned inline trough the following installation wiki.

Pre-install
 - requirements
 - download EFI
 - download PropperTree & GetSmbios
 - get your MAC address
 - Make sure of proper display cable connection

2. Building the installation USB
 - From Windows
 - From macOS (physical or Virtual Machine)

3. Update BIOS & change variables
 - Update bios
 - Bios needed changes
 - Grub commands

4. Install
 - Partitions setup
 - Set-up up account and final steps.

5. Post-install 
- Copy EFI from USB to SSD partition
Sleep terminal commands
Energy Saver

6. Troubleshooting

7. Installing additional hardware
  - Wfi’s
  - dGPU’s
  - etc.

8. Useful tools for this Hackintosh
 - Hackintool
 - Opencore Configurator
 - RDM

Special Thanks to ….

**Comment by Kinetik** [comment]
The good thing about wiki pages is that you have room to dive in deeper details and pictures, and still keep track of the installation steps. 

What you have now in the Wiki section is basically a sectioning of your current readme.md. 

If you want to go with my suggestion, we must first properly create each page. And after that change the readme.me to this template.

**Comment by Kinetik** [comment]
I also created 2 projects for you to look at and figure out if you want to use them. Check them out.

Unfortunately for me my new Mac mini will not come this month, I had to postpone the purchase. So, I have  some more time with you to set this up. As it is a nice personal project for me too, I hope you find some of this useful.

**Comment by Kinetik** [comment]
Another idea is to switch to Github Pages (like the Dortania guide) 
https://pages.github.com

**Comment by Kinetik** [comment]
It's so easy to set up initially, I think 10 min and you're done. 

The information set-up and pages will take a lot longer. But even for that, initially, you can just paste the readme to the main page, and change/add to it step-by-step later.

**Comment by Kinetik** [comment]
Also, please enable the Discussions for this repository. 
https://docs.github.com/en/discussions/quickstart

As of now, we are having discussions in the issues list. Both topics are not actual issues.

**Comment by Kinetik** [comment]
The Issues Tracker project I've created, will contain all newly created issues, shown as cards on the right side of the page.
All you have to do is drag and drop the card to the desired column, and save. I hope you find it useful.

**Comment by Kinetik** [comment]
If you want to go with Pages, then you should disable the Wiki for this repository, in the same place you enable the Discussions. Under Settings, scroll down, the Feature section. To disable/enable a feature, just check the boxes.
<img width="1436" alt="Screenshot 2021-05-26 at 16 07 45" src="https://user-images.githubusercontent.com/56897038/119665416-0a4c7f00-be3d-11eb-943e-7c20ad87c205.png">

<img width="1436" alt="Screenshot 2021-05-26 at 16 08 58" src="https://user-images.githubusercontent.com/56897038/119665437-0f113300-be3d-11eb-9043-af8caf551c09.png">

**Comment by Kinetik** [comment]
Any thoughts @varszegimarcell ?

**Comment by Xtendera** [comment]
@Kinetik, Github pages would we cool and helpful, but it isn't easy building a good-looking easy-to-use guide website. The for the dortania guide, for example, is made manually in Vue.js, CSS, and markdown. I say we go with the wiki solution, just so we don't unnecessarily spend weeks on something we don't need. If you still want to go for Github pages, try more premade solutions like [Course-in-a-box](https://course-in-a-box.p2pu.org/) or similar.

**Comment by Kinetik** [comment]
It's not that difficult, because you can use an already made template. There are more available tools in pages now, then when dortania created the guide. Just have to create the repositories and start with 1 page, probably copy paste from the existing. It takes 30 min max, with reading instructions.
But fist you need the individual pages and you can use the existing wiki section to create them, and when ready, create the github.Pages, just as a suggestion.

**Comment by Kinetik** [comment]
I think i will back down from this project. You have all my suggestions.
@varszegimarcell is too unresponsive for my taste when discussing an active project. I understand that he is busy, but i have to keep busy also. I am working from home and have a lot of free time and want to invest in personal projects. This seems to go very slow even with basic communication. 

I will still offer support whenever i can, buy i will no longer be active on this project. Hackintosh is working well now, time to take a brake. 

Cheers!

**Comment by Xtendera** [comment]
I know this is about the guide, but today in WWDC 21 macOS 12 Monterey officially dropped support for Haswell chips. I'm pretty sure OpenCore will find a way to make it work, but I guess they are really pushing towards the M1.

**Comment by Xtendera** [comment]
Also, I am working on a more clear guide based on the initial project structure. The new guide is on the guide-reformatting branch.
