### ISSUE TITLE
Wrong ig-platform-id for i3-4150

### ISSUE THREAD

**Issue by darkymtp** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#3]
I had to change ig-platform-id to 0D220003 to be able to start installation process.
My CPU is the stock i3-4150.

**Comment by varszegimarcell** [comment]
Hello

Thanks for the feedback. Firstly, I've also installed Mac with i3-4150 CPU, but for me, it worked with the original framebuffer, included in the config.plist. 

Can you please tell me, that did you installed Catalina or Big Sur? 

Do you have graphics acceleration?

Do you have issues with opening lagre (4K etc.) resolution images using the preview app? Does the app produce graphics glitches or freezes? 

In my case, I had these issues, and I was only able to solve it with a CPU upgrade, and I've experimented a lot with my HD4400 equiped CPU. Freezez in GarageBand were especially annoying.

**Comment by darkymtp** [comment]
Hello.
I'm using Catalina.
I have graphics acceleration, 1440p 60Hz, 1536MB graphic memory.
Opening large pictures leads to freezes and bugs.
Well, it's time to look for i5 4590 or low profile graphic card.

**Comment by varszegimarcell** [comment]
> Hello.
> I'm using Catalina.
> I have graphics acceleration, 1440p 60Hz, 1536MB graphic memory.
> Opening large pictures leads to freezes and bugs.
> Well, it's time to look for i5 4590 or low profile graphic card.

That’s why I do not recommend using a HD4400, but it is usable for the basic stuff.

Sometimes, you may need to change the the platform-id to make the system work, but I have no idea why. As far as I know, the recommended AAPL,ig-platform-id is 0300220D, so that’s why I include it in the config. This config worked with my i3-4150, for sure, but I had the same glicthes as you, so I upgraded CPU. These Haswell CPUs pretty cheap these days.

**Comment by darkymtp** [comment]
I tried again, full wipe internal SSD and USB key.
In fact, I can change AAPL,ig-platform-id value to 12345678, it works.
Keeping 0300220D is giving me black screen but...
I found that connecting  another monitor to the PC makes it work as attended.
The 'new' monitor is connected via DVI-DP cable, 1080p.
My main monitor is 1440p DP-DP.
Removing 'enable-hdmi20' fixes that.
