### ISSUE TITLE
1080p HiDPI on 2k and 1080p monitors

### ISSUE THREAD

**Issue by Kinetik** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#34]
An iMac SMBIOS expects to have a 5k display output. 
For our machine a DisplayPort connection is seen as a built-in. 
<img width="640" alt="Screenshot at May 16 12-31-33" src="https://user-images.githubusercontent.com/56897038/118392487-ac50b800-b642-11eb-82dc-d6e9640f4c7a.png">

We cannot buy 5k monitors because they are very expensive, so what this means to us is, if we use a 4k monitor (closest match) we will have enabled, by default, the Retina bar selector with all HiDPI resolutions except the 4k one (last one).

![115268432-eeb9ce80-a142-11eb-8e94-94853695a418](https://user-images.githubusercontent.com/56897038/118391845-02236100-b63f-11eb-929a-a8779bd577e1.jpg)

If you use a 2k monitor or a 1080p one you will NOT get any HiDPI enabled. The problem here being that even at 2k native resolution the image is still very unsharp. That is why a 1080 HiDPI resolution is looking a lot better and usable than a 1440 unsharp image.

If you use a 5k 5120x**2880** Monitor, you will get 1440 and 1080 with HiDPI by default.
If you use a 4k 3840x**2160** Monitor, then you will only get 1080 with HiDPI by default. 
If you use a 2k 2560x**1440** Monitor, no HiDPI resolution available
If you use a FullHD 1920x1080 Monitor, no HiDPI resolution available

Retina display means increased pixel density display. Most monitors found on the market have between 90 and 110 pixels per inch (ppi). Retina displays have double that, over 200 ppi. That is why a native resolutions appears as hiDPI on Retina displays (no need for upscaling to achieve it)
https://www.binarytides.com/find-high-ppi-monitors/
HiDPI means x2 the pixel count. Basically, in order to achieve a 1080 HiDPI resolution, your display must be capable of double of that. Means 2160, witch is the 4k.

Luckily with Big Sur now you can add manually resolution with proper flags without having to disable SIP.
You can trick the IGPU output to consider that resolution even if the monitor does not support it. On a 1080p monitor, the iGPU will output double x2 to create the HiDPI. Your monitor will still run at 1080, but enhanced.
Some guys created a nice app "RDM", that lets you add to your registry a manual entered resolution.
https://github.com/usr-sse2/RDM
Head over to the latest releases and download it. 

I tested this on a 2k 75hz monitor, for with I am enjoying a FullHD HiDPI resolution still at 75hz. 
It added the 4k scaled option but at (low resolution). Not of interest on lower Rez monitors (too small anyway)
<img width="661" alt="Screenshot at May 16 12-11-13" src="https://user-images.githubusercontent.com/56897038/118391995-d3f25100-b63f-11eb-802d-555f7cd49e1a.png">

What you have to do:
1. Launch the app. It will launch in the menu bar.
2. At the end of the resolutions list hit the Edit button
<img width="179" alt="Screenshot at May 16 12-12-41" src="https://user-images.githubusercontent.com/56897038/118392045-19af1980-b640-11eb-856a-1f27f7cb25f5.png">
3.  Hit the + sign at the bottom of the window, manually add the 1920x1080 width and height and check the first three checkboxes as seen below
<img width="685" alt="Screenshot at May 16 12-14-44" src="https://user-images.githubusercontent.com/56897038/118392111-790d2980-b640-11eb-85fc-2e573e5e1e31.png">
4. Hit Save and **Reboot**

On reboot you will get the 1080 HiDPI as Default for display. Enjoy!🤩
<img width="658" alt="Screenshot at May 16 12-20-36" src="https://user-images.githubusercontent.com/56897038/118392221-297b2d80-b641-11eb-8c4f-4fbcc86a9161.png">

Look for the little lightning bolt and select that one:
<img width="337" alt="Screenshot at May 16 13-45-32" src="https://user-images.githubusercontent.com/56897038/118394387-20905900-b64d-11eb-9554-06b409cf1aab.png">

I'm looking for someone to please test this with a 1080p monitor and a Displayport connection (no HDMI).
I want to create a Wiki page with this, but needs testing on FullHD monitor. But I think that with a 1080p monitor, the tester should not try the 4k resolution even if it appears in the list (could get a black screen). Thanks!

**Comment by Xtendera** [comment]
Hey Kinetik, 
I do have a 1080p display. But my monitor does not have a DisplayPort slot, so I use a DP -> HDMI converter. I can still try it though, but I can't try any experiments right now as I am still using my hack to join zoom for school. School ends on Friday for me, so I can try it in 3-4 days.

**Comment by Kinetik** [comment]
https://www.binarytides.com/find-high-ppi-monitors/

**Comment by Xtendera** [comment]
I bought a pretty branded and costly adapter, but it doesn't say if it is 1.2 or 1.4. I don't want to launch the program during school as I don't want any issues, but I will certainly test it on Friday. 😃

**Comment by Xtendera** [comment]
https://www.amazon.com/DisplayPort-Adapter-Converter-Gold-Plated-Compatible/dp/B017Q8ZVWK/ref=sr_1_2_sspa

**Comment by Kinetik** [comment]
It's possible you will get only 60hz out of that, or 4k at 30hz. Good luck!

**Comment by Xtendera** [comment]
OK

**Comment by varszegimarcell** [comment]
I will try it out too. I never heard of this HiDPI stuff before, as I never had a real Mac. Sorry about that, I may got used to some stuff without noticing that it isn’t right, and it isn’t supposed to work like how it is now. 😂🤣

**Comment by Xtendera** [comment]
Hey Kinetik,
As you were saying, I did not get HiDPI. But I was able to have 1080p@75hz with the program. That is the max resolution and refresh rate of my monitor. Sorry I wasn't able to test out HiDPI. I cannot buy any monitor which does have DP because I just got a new one and do not have the budget for another one. Sorry!

**Comment by Kinetik** [comment]
Hey. Well this answers your question also if your adapter supports 1.2 or 1.4 conversion. Usually the 1.4 witch is capable of handling 4k at 60hz (or 1080 at 144hz) costs above 15 dollars or euro. If the description does not specify, the price is usually an indicator. 

Too bad, you would have enjoyed the clear (Mac like) resolution, or closest match at least. HiDpi does not compare with retina, retina is best and better just because in does not stress the iGPU to produce this clearness, it's native. But still, it's the best you can achieve on low ppi normal desktop monitors

**Comment by Kinetik** [comment]
@Xtendera you can try the 1280x720 resolution as HiDPI. That might work for you.
<img width="804" alt="Screenshot 2021-05-25 at 20 38 09" src="https://user-images.githubusercontent.com/56897038/119543561-74134d00-bd99-11eb-9128-09d5587e2b16.png">
<img width="181" alt="Screenshot 2021-05-25 at 20 38 36" src="https://user-images.githubusercontent.com/56897038/119543579-77a6d400-bd99-11eb-976f-94ae411e797d.png">

**Comment by Kinetik** [comment]
Also select a iMac icon from the list before hitting Save-> 
<img width="804" alt="Screenshot 2021-05-25 at 20 42 09" src="https://user-images.githubusercontent.com/56897038/119543812-c18fba00-bd99-11eb-8530-8fc5031124d8.png">

**Comment by Xtendera** [comment]
OK, I'll try right now.

**Comment by Xtendera** [comment]
Well, it doesn't have the little lighting bolt beside that either. So I guess my adapter doesn't support HiDPI at all.

**Comment by Kinetik** [comment]
Yes. It's most likely the issue. Did you reboot after each save?

**Comment by Kinetik** [comment]
Here is the difference for the 1080p Resolution with HiDpi and without it (normal).

1080 Normal
![Screenshot 2021-05-25 at 22 39 39](https://user-images.githubusercontent.com/56897038/119558715-6d410600-bdaa-11eb-8867-7047e0d354e3.png)

1080 HiDPI
<img width="388" alt="Screenshot 2021-05-25 at 22 39 02" src="https://user-images.githubusercontent.com/56897038/119558730-75994100-bdaa-11eb-9509-ad1d48dd8344.png">

1080 Normal
![Screenshot 2021-05-25 at 22 40 16](https://user-images.githubusercontent.com/56897038/119558771-83e75d00-bdaa-11eb-9aa2-405cd88d7b8e.png)

1080 HiDPI
<img width="252" alt="Screenshot 2021-05-25 at 22 40 28" src="https://user-images.githubusercontent.com/56897038/119558794-8a75d480-bdaa-11eb-9eac-cb019a1ebed5.png">

**Comment by Xtendera** [comment]
I got HiDPI! And not 720p, 1080p! All I needed was a restart, and it shows a lighting icon beside 1920x1080p! Here is a screenshot:
<img width="316" alt="HiDPI" src="https://user-images.githubusercontent.com/67883305/119574703-7f578000-bd7b-11eb-80c8-b786b333f5c9.png">

**Comment by Kinetik** [comment]
I'm glad, enjoy it! I guess now you and others can understand what i was talking about all this time.


Probably next i will try to make everyone understand the framebuffer patch. Without it you will never get this. Basically what that does, is allocating fbmem 32 mb from the device-id standard, and we are changing it with our patch to 48mb. This gives us 4k and hiDPI + some other tweaks from the boot-args.

**Comment by varszegimarcell** [comment]
Hey!

I've tested this on a 1080p@144Hz display, connected via DP. 

Everything looked much sharper, although it is not hugely noticeable difference on a 24" display. 

However, the RDM patch seems to mess up 144 Hz refresh rate. The monitor still runs at the desired refresh rate, but the smoothness of the animations are gone when I use the HDPi mode. My guess is that the iGPU cannot render frames this fast when in HDPi mode. This is also verified for me via the UFO Test, as the frames there render correctly, and I see the high refresh rate difference between the UFOs. (https://www.testufo.com) Seems like the UI rendering becomes much harder for the iGPU, and cannot produce 144 FPS. 

I will try to mess around with it later, trying to get the high refresh rate work properly, but if it is a hardware limitation (which I suspect is...) might not be able to work out properly.

**Comment by Kinetik** [comment]
Hi. Yes, there is a hardware limitation with this iGPU. But if you disable the Transparency, then everything still looks good are runs faster. 

<img width="780" alt="Screenshot 2021-05-26 at 11 28 29" src="https://user-images.githubusercontent.com/56897038/119628193-8a5eee80-be15-11eb-81d3-a4c0f17347f3.png">
