### ISSUE TITLE
Cannot shutdown and sleep then never wakeup

### ISSUE THREAD

**Issue by hieunhuit** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#35]
Hi, I just installed the bigsur 11.3 when I try to shutdown, the system would be automatically restart again or sometime it not completely turn off, cpu fan and power button light is still work. 
Another issue, sleep is not working also, I put it to sleep but it cannot be wakeup even I push to power button.
The ethernet port is not working, unplug state come up when the cable is connected. I try to update the RTL8111 kext and it work again :)
But I am very happy with almost thing work well. Please take a look, thank you.

Dell optiplex 3020 MT
i7 4770
16GB DDR3
SAMSUNG 860 EVO sata 3

**Comment by Kinetik** [comment]
Hello. I very sure it is because of the new USBMap.kext and because your port mapping on the MT is different then the SFF. @varszegimarcell this I think answers your question too. 

I suggest that you switch back to usbinjectall or go trough the usbportmapping guide to create your own USBMap.https://dortania.github.io/OpenCore-Post-Install/usb/manual/manual.html#usb-mapping-the-manual-way

**Comment by hieunhuit** [comment]
I do the easier way which is show me mapping the USB port then it still stuck on this issue.
After that, I tried to move whole system from 3020 MT to 3020 SFF  then no different, still restart after shutdown.

**Comment by Kinetik** [comment]
I am going to make the mapping again soon, maybe I missed something.

**Comment by Kinetik** [comment]
I think this is what is needed: https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html

**Comment by Kinetik** [comment]
But, for the record, I think you are the only one that has this issue. Check if you changed something in the config. 
Please check the latest release of the efi package.

**Comment by Kinetik** [comment]
Try this, let me know if it solves the issue:

1. Add this file to your ACPI folder 
[FixShutdown-USB-SSDT.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6502794/FixShutdown-USB-SSDT.zip)
2. Add this section to your plist, under ACPI->Patch 
[FixShutdown-Patch.plist.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6502798/FixShutdown-Patch.plist.zip)
3. Add the new file under ACPI->Add->2

Like this:
<img width="1418" alt="Screenshot 2021-05-18 at 19 15 03" src="https://user-images.githubusercontent.com/56897038/118687591-de624580-b80d-11eb-846f-0f0e891ff591.png">

**Comment by hieunhuit** [comment]
Yes, I did that but nothing happened
![Screen Shot 2021-05-18 at 23 31 20](https://user-images.githubusercontent.com/48056637/118689640-6d348980-b831-11eb-9a19-b0a85b158fb8.png)
![Screen Shot 2021-05-18 at 23 31 34](https://user-images.githubusercontent.com/48056637/118689664-732a6a80-b831-11eb-8bf2-d3ea653cc7ed.png)

**Comment by Kinetik** [comment]
I don't know what to tell you more. You are the only one claiming this behaviour as of yet. If anyone else claims this, then it is a general MT problem, if not, consider you have something wrong with the unit.

**Comment by hieunhuit** [comment]
I've usb mapping serveral time, but it's still not working even I do with the SFF. Could I ask some Q, Which Big sur version and BIOS version you are in? Sorry I'm a newbie and something quite difficult to understand. I so glad if you have a full video about installation. I'm really really appreciate that. Thank you so much

**Comment by Kinetik** [comment]
Bios version should be A20. Everything you need is in the Installation guide. You just have to download the latest EFI package, add a valid SMBIOS, your MAC address and before installation use the grub shell to execute the bios changes. That is it! 

All this, of course, if you use the standard hardware for this unit. If you have additional graphic boards, or ethernet cards etc. You must search the web and configure those by yourself. If you use the config as it is with additional hardware, is most likely that even the basis hardware will not work anymore.  In this case, if you want a Hackintosh, you must dedicate some efforts and figure out for yourself. If you have the basic hardware, went trough all the steps and still you have problems, consider you have something faulty with the unit. Cheers!

**Comment by hieunhuit** [comment]
Hi, good news :), After I turn off the MST on my monitor DELL U2419H, now it could be shutdown, restart even sleep, everything is working as well. I so lucky when I disconnect the DP cable and use VNC to remote and control screen, then I turn off, wow surprise, finally, it's actually shutdown. Next, I remember that I have enabled MST in my monitor setting before, I set it to disable, and so on. :))

**Comment by Kinetik** [comment]
I have to say it!   JEZASS!!! 🤯🙄

**Comment by hieunhuit** [comment]
After 2 days, everything is stable. Thank you for your help Kinetik :D
