### ISSUE TITLE
Slow Boot Since 1 month

### ISSUE THREAD

**Issue by mmfixemer** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#39]
Hi,
i didnt think much of the boot time till i updated the EFI Folder today with the new Update ( thanks agin for the update Mac is running even smoother now). When i did the update i saw a lot of log file in the EFI Partition, maybe you could have a look and let me know if you have any idea why i get so many log files. the first log is from March 18th, i will attach the first and the last log after the EFI update.
Thanks Again for the incredible support and Git for our little Machine.

Best Regards Mike
[opencore-2021-03-18-195713.txt](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6564971/opencore-2021-03-18-195713.txt)
[opencore-2021-05-29-161219.txt](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6564972/opencore-2021-05-29-161219.txt)

**Comment by Kinetik** [comment]
Hi. You can just delete those. They are boot logs, usefull for debugging. 
As you are not doing any debuging, like most users of this EFI, the config should be changed to not generate these anymore.

This should be followed IN REVERSE (means whatever is istructed, change to NO and lower values):
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html#opencore-debugging
