### ISSUE TITLE
EFI Configuration 

### ISSUE THREAD

**Issue by JohnAker33** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#43]
>  Although generating serials are possible post-install, I would not recommend it, doing these tasks now can save a lot of pain and troubleshooting later, especially when you trying to make iMessage work. 

I'm not clear on why it's suggested to generate serials first to the config.plist before the installation. Why does it make any difference ? Would you explain that more in depth ?

**Comment by JohnAker33** [comment]
Here is the USB Ports kext I made from my 3020 MT if you want to use it for your guide readers. It lets them use the board's internal USB 2.0 header (blue) for a BT/Wifi card. Also includes the rear panel USB 3.0 ports. 

[USBPorts.kext.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6801042/USBPorts.kext.zip)

**Comment by Kinetik** [comment]
If you have any Apple product (iPhone, iPad etc) you probably know that when you first power it up, it does a device activation, and after that is successful it allows you input you iCould account. This is similar. You have to provide a valid serial number ( 3 serials actually) before you can have a working iCloud account on you Hackintosh. 
If you do not plan on using a iCloud account with your machine, then leave the config sections empty (except MAC...you need that for ethernet connection) and it will work. 

You can install without, but adding the serials after will give you a lot of error pup-up along the way...you will have to input your iCloud password a bunch of times and it's frustrating. That is why it is recommended to find a working serial number before install.

**Comment by JohnAker33** [comment]
Thanks for explaining that. Makes sense to create serials and add them to the USB installer first.

**Comment by JohnAker33** [comment]
It looks like I'm getting 4K @ 60Hz on my 4K television. Didn't know this was possible using HD4600 iGPU. Great work by everyone on this project. Very happy with the results. 

![Screen Shot 2021-07-17 at 2 38 58 PM](https://user-images.githubusercontent.com/79269523/126052447-cdeba168-95a9-4fe0-a614-b106c22e640c.png)

![Screen Shot 2021-07-17 at 7 23 58 PM](https://user-images.githubusercontent.com/79269523/126052450-edb08fd2-33d2-44f8-aeae-4a297628ba40.png)
