### ISSUE TITLE
MacOS 12 Support in the future

### ISSUE THREAD

**Issue by varszegimarcell** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#45]
Hi!

First of all, I would like to say a big thank you for maintaining the project instead of me, I completely forgot about checking Github in the past month or so. I saw the new guide, which is just much better in every way I wrote, and also thanks for keeping up with OpenCore updates.

Second, I want to discuss the case of MacOS Monterey 12, the next release of MacOS. As you've may noticed, Apple will drop support for iMac 15,1 and below, so I'm not sure if we can use the 4th gen Intel platform it the future for an up-to-date Hackintosh build. It is possible that we may be able to fake the machine as a Macbook instead, but I'm not completely sure about it. The late 2015 iMac used a 6th gen Intel processor, so it can cause issues with graphics. If we will be that unlucky, maybe Apple can just simply remove HD4600 support. 

What do you think, how should we approach the version change? I want to use this issue as a discussion thread, so please feel free to post your ideas. If it is possible, I want to keep on using this machine in the future, hopefully not stucked on Big Sur.

**Comment by Xtendera** [comment]
Hi,

I had also been thinking about Monterey and what we should do. My current plan is to try it on my computer, and see how well it works. In fact, just today I updated to the latest OC and kexts to get ready to join the beta program. I am still trying to find a hard drive to try it on, but I'll manage.

If things don't work out, we might have to archive this repo, but the release of Monterey is still a bit away, so let's wait.
I'll keep ya posted!

Also, as Kinetik suggested, it would be good if you could enable the Discussions feature. This way we don't have to talk in issues or PRs.

**Comment by JohnAker33** [comment]
I've already installed the Monterey Beta and it does work with iMac 15,1 if you use the -no_compat_check boot flag. This doesn't work for updates so it may be better to use Mac mini 7,1 instead for the long haul as that uses a Haswell CPU and not Skylake. 

https://everymac.com/ultimate-mac-lookup/?search_keywords=Macmini7,1

**Comment by Xtendera** [comment]
Thank you for this information. Yes, I have also been able to boot Monterey with the flag, but am still working on the mac mini fix.

**Comment by JohnAker33** [comment]
Someone should also look into iMac 16,1 SMBIOS which was Broadwell and Iris Pro 6200 Graphics based. 

![Screen Shot 20](https://user-images.githubusercontent.com/79269523/126727577-b99dc27f-35bd-42dc-b242-e3b6417b9de9.jpg)

**Comment by Xtendera** [comment]
Hey, a quick update on Mission Monterey.

Big Sur installs just fine while faking the iMac16,1 machine as @JohnAker33 suggested. But when I got to update, it just comes back with nothing changed, so I am currently trying to make a macOS 12 installer that I can use to update.

**Comment by Kinetik** [comment]
Remember to always also change the USBMap.kext with the new iMac gen. Otherwise it will probably not even boot corectly.

For me it's not worth updating. Monterey comes with improvements in comunication tools and a 10% visual improvement. All these required my the pandemic situation. Probably next os will have updates worthy of upgrading, but that is a long way away. Probably for the next one there will no workaround for this machine. 

These 3020 serises were bought by companies in 2014-2015 and were made available for us in around 2019. I thing we have reached it's maximum capabilities and we should look to upgrade to the next gen of optiplex (that companies bought around 2017 😃 ). Future updates of opencore will probably increase it's performace over time...but not by much. 
This machine was most compatible with the iMac 14.2, but we could strech it and with faking the igpu and use the 15.1, but that is actually a max strech for this machine. I think that from this point on...trying to make it work with newer Os's it's a messy and dissapointing battle, with a lot of risk. 

I am keeping on 11.5, will probably update the opencore once a year, and that is it. I enjoy it as is. Good luck to you all, i am not joining this battle.

**Comment by Xtendera** [comment]
Hey Kinetik,
This isn't a problem for me as I just use USBInjectAll as my machine is a MT and they seem to have issues on it.

**Comment by varszegimarcell** [comment]
> Someone should also look into iMac 16,1 SMBIOS which was Broadwell and Intel HD 6000 Graphics based. 16,2 is also a 21.5" Broadwell iMac using iGPU. That may be the best fit.
> 
> > The late 2015 iMac used a 6th gen Intel processor, so it can cause issues with graphics.
> 
> The 21.5" iMacs mentioned above were 5th Gen Broadwell and are closer to the previous Haswell generation. Iris Pro 6200 graphics could be spoofed. Many Haswell Z97 motherboards even supported Broadwell i5s and i7s.
> ![Screen Shot 20](https://user-images.githubusercontent.com/79269523/126727577-b99dc27f-35bd-42dc-b242-e3b6417b9de9.jpg)

The problem with the Iris Pro 6200 is that although  they're from the same generation of graphics with the HD4600 iGPUs, they're architecturally pretty different. The Iris series of integrated graphics featured dedicated video memory, and by that, I can only assume that the drivers can work pretty differently, and introduce a whole bunch of new graphics related bugs, even if they work. As far as I know, MacOS determines which drivers to use based on the machine ID. 

Also, until the final release, we cannot be sure that the HD4600 drivers will stay in the system. We've seen multiple times that the beta releases still contained older drivers, which were removed by the later beta releases. 

My best bet would be to fake the machine as a MacMini7,1, as it contained still a Haswell CPU. The only problem, that it used an iGPU called Iris 5100, which to me not seems too different form the specs of a HD4600. 

There are only two Boradwell CPUs, that may be theoretically compatible with the Z97 chipset, which are the i5-5675C, and the i7-5775C. I hadn't found anything yet that would verify compatibility form Dell's site, I will keep looking on that topic. The only problem that these CPUs are not as common as other Core desktop CPUs. If these CPUs are compatible, it would make the iMac Late 2015 way passable.

**Comment by varszegimarcell** [comment]
I enabled discussions BTW :)

**Comment by JohnAker33** [comment]
"There are only two Broadwell CPUs, that may be theoretically compatible with the Z97 chipset, which are the i5-5675C, and the i7-5775C. I hadn't found anything yet that would verify compatibility form Dell's site, I will keep looking on that topic."

Dell would have had to add support via a BIOS update but I don't believe they ever did. It still wouldn't hurt to try one and see what happens. They are widely available on Ebay. They never supported the 4690K or 4790K but both of those still work.

**Comment by JohnAker33** [comment]
> > Someone should also look into iMac 16,1 SMBIOS which was Broadwell and Intel HD 6000 Graphics based. 16,2 is also a 21.5" Broadwell iMac using iGPU. That may be the best fit.
> > > The late 2015 iMac used a 6th gen Intel processor, so it can cause issues with graphics.
> > 
> > 
> > The 21.5" iMacs mentioned above were 5th Gen Broadwell and are closer to the previous Haswell generation. Iris Pro 6200 graphics could be spoofed. Many Haswell Z97 motherboards even supported Broadwell i5s and i7s.
> > ![Screen Shot 20](https://user-images.githubusercontent.com/79269523/126727577-b99dc27f-35bd-42dc-b242-e3b6417b9de9.jpg)
> 
> The problem with the Iris Pro 6200 is that although they're from the same generation of graphics with the HD4600 iGPUs, they're architecturally pretty different. The Iris series of integrated graphics featured dedicated video memory, and by that, I can only assume that the drivers can work pretty differently, and introduce a whole bunch of new graphics related bugs, even if they work. As far as I know, MacOS determines which drivers to use based on the machine ID.
> 
> Also, until the final release, we cannot be sure that the HD4600 drivers will stay in the system. We've seen multiple times that the beta releases still contained older drivers, which were removed by the later beta releases.
> 
> My best bet would be to fake the machine as a MacMini7,1, as it contained still a Haswell CPU. The only problem, that it used an iGPU called Iris 5100, which to me not seems too different form the specs of a HD4600.
> 

I was thinking along the lines of a SMBIOS that would work for those with a dedicated GPU. The SFF or MT allows the use of a supported graphics card, some of the older Nvidia cards still work and eventually AMD prices will come back down again. The it won't matter that HD4600 still has support or not.

**Comment by Xtendera** [comment]
Hey,

I will not be able to work on this repo that much anymore as school is starting, and I am going to be busy with homework. I may have time to work on the weekends though. 👍🏽

**Comment by Xtendera** [comment]
#62 
I'll close this.
