### ISSUE TITLE
Ethernet doesn't work

### ISSUE THREAD

**Issue by wannadream** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#5]
Hi, first of all, thanks for your work.

I've followed the guide and successfully installed Big Sur on a Dell 3020M. It is weird that the ethernet card is recognized in MacOS but it doesn't work, light not flashing after I plugged in the cable. It does work normally in Windows. Do you have any clue what may cause the issue? Is that related to the Realtek Kext?

![Screen Shot 2020-02-08 at 1 37 23 AM 1](https://user-images.githubusercontent.com/6989212/103587420-70436480-4ea4-11eb-9a0f-f779e621aeba.png)

Thanks in advance for any suggestion or thoughts.

**Comment by varszegimarcell** [comment]
Hello

Sorry about the late response, I was busy with my graduation.

 Well, I've found in the OpenCore "Gathering files" guide, that in some cases, the Realtek kext is buggy, and in that case, you have to downgade it to an older version.
 
 
![kép](https://user-images.githubusercontent.com/47447944/103897780-5304d500-50f4-11eb-93c7-67f2feba76ea.png)
Source: https://dortania.github.io/OpenCore-Install-Guide/ktext.html#ethernet

Let me know how it goes.

**Comment by wannadream** [comment]
Thanks for the hint, I will try it out.

**Comment by wannadream** [comment]
It worked, thanks!

**Comment by varszegimarcell** [comment]
Happy to hear that!

I have no idea why in some cases the new kext refuses to work. Maybe it has something to do with the ethernet chipset firmware.
