### ISSUE TITLE
Can't boot Just Show Apple Logo

### ISSUE THREAD

**Issue by Rivaldi72** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#57]
I have done all the steps but cant boot into installer

**Comment by Rivaldi72** [comment]
[EFI Big Sur.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/7118295/EFI.Big.Sur.zip)

**Comment by Xtendera** [comment]
Have you disabled CFG lock?

**Comment by Rivaldi72** [comment]
I already follow step to disabled CFG Lock, but get the same issues

**Comment by Rivaldi72** [comment]
![IMG_20210907_093209](https://user-images.githubusercontent.com/26193783/132275489-2149b40c-7452-4a8c-b686-24c564e36911.jpg)
![IMG_20210907_093438](https://user-images.githubusercontent.com/26193783/132275497-713b412c-3fd7-48f9-9005-df2768483687.jpg)

**Comment by Xtendera** [comment]
Try replacing the opencore binaries with the debug ones. Or, check the logs.

**Comment by Rivaldi72** [comment]
Okay all done with change bios to default and set again
