### ISSUE TITLE
Intel i5-4590T

### ISSUE THREAD

**Issue by wannadream** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#6]
I swapped the CPU with a i5-4590T. Now, I could not boot into the system. Getting error below:

![PXL_20210109_001314668](https://user-images.githubusercontent.com/6989212/104076980-0fce6300-51d5-11eb-9a63-0e67e05522e3.jpg)

I am wondering if I need to update the config.plist, still going through documentation of OpenCore.

**Comment by varszegimarcell** [comment]
Hello

The CPU swap usually resets the NVRAM variables too. You have to redo the command line stuff to set the variable values. Typically, when the boot process stucks in this state, the CFG lock is not disabled.

In theory, you have to do nothing with the config.plist, except when you’re faking CPU IDs, which in this case is simply not needed.

**Comment by wannadream** [comment]
Thanks for the hint. I will have a try.
