### ISSUE TITLE
Donation for a new CPU?

### ISSUE THREAD

**Issue by jayphizzle** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#7]
Hi!

I'm following your guide a few weeks and got my 3020M running with Big Sur without issues.
i would like to give something back and help you buying a new cpu.
do you accept donations?

regards

**Comment by varszegimarcell** [comment]
> Hi!
> 
> I'm following your guide a few weeks and got my 3020M running with Big Sur without issues.
> i would like to give something back and help you buying a new cpu.
> do you accept donations?
> 
> regards

Hi!

I would be very thankful if you would support to buy a new CPU into my 3020SFF.

You can send me as much as you wish to my PayPal account: varszegimarcell@gmail.com

Thank you! :)

Cheers
M

**Comment by jayphizzle** [comment]
What do you need/want for a new CPU? Perhaps I can send you one instead ;)

**Comment by varszegimarcell** [comment]
> 
> 
> What do you need/want for a new CPU? Perhaps I can send you one instead ;)

Well, anything that fits into an LGA1150 socket, with HD4600 graphics would make me happy :D

I have an i3-4150 as a backup CPU, which works, but with Big Sur, the graphics is extremely glitchy with a HD4400, to the point that the system is unusable.

**Comment by jayphizzle** [comment]
I hope my small donation will help you ;)

**Comment by varszegimarcell** [comment]
> 
> 
> I hope my small donation will help you ;)

Thank you! It will help for sure :)
