### ISSUE TITLE
Bluetooth Working?

### ISSUE THREAD

**Issue by jayphizzle** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#8]
Hi!

I'm using the 3020M with a BCM94360NG M.2 Card.
Wireless is working fine but I can not connect or see any bluetooth device.
I want to use the original Apple Magic Mouse and Keyboard.
I have no Antenna installed and see this as the reason for the bluetooth problem.
But perhaps there is another issue?

How can I check if bluetooth is correct configured?

Thx!

**Comment by varszegimarcell** [comment]
Hey!

As far as I know, this Bluetooth chipset should be plug and play with MacOS. Does the OS recognizes the Bluetooth card? You can check it in Apple icon > About this Mac > System report.

I think you must have a Bluetooth antenna installed for reliable connection, but to make sure that your card is OK, I would start the computer with an open case, and place the bluetooth device as close as possible to the antenna sockets of the card. If it can pair, your card is fine.

**Comment by varszegimarcell** [comment]
Unless you do not want to run your computer all the time with open case, you must install an antenna. After further thinking, I realized that the computer case is made from metal (aluminium or steel, doesn't matters),  which is connected to ground via the power supply grounding. So, your computer case basically acts as a Faraday cage, thus no radio signals can penetrate the case. 

This is clearly visible on metal bodied smartphones for example. You can always see these plastic lines on the body of the phone: 
![kép](https://user-images.githubusercontent.com/47447944/107941310-d1715400-6f89-11eb-8853-29b5b8b585fd.png)
That's the reason behind these plastic lines too. The antennas are behind these plastic strips.

**Comment by jayphizzle** [comment]
> As far as I know, this Bluetooth chipset should be plug and play with MacOS. Does the OS recognizes the Bluetooth card? You can check it in Apple icon > About this Mac > System report.

Looks ok for me:

![Greenshot 2021-02-20 21 06 52](https://user-images.githubusercontent.com/9048913/108607296-c3736700-73bf-11eb-9d7b-09132e650079.png)

I will try it with a open case.

**Comment by varszegimarcell** [comment]
> 
> 
> > As far as I know, this Bluetooth chipset should be plug and play with MacOS. Does the OS recognizes the Bluetooth card? You can check it in Apple icon > About this Mac > System report.
> 
> Looks ok for me:
> 
> ![Greenshot 2021-02-20 21 06 52](https://user-images.githubusercontent.com/9048913/108607296-c3736700-73bf-11eb-9d7b-09132e650079.png)
> 
> I will try it with a open case.

Looks good to me etiher.

**Comment by jayphizzle** [comment]
After I got a new wifi antenna, bluetooth is working fine now.

Apple Magic Mouse and Keyboard are connected and working from a distance on my desk.
