### ISSUE TITLE
Experience with 'Dell WFJ0V Display Port Card' ?

### ISSUE THREAD

**Issue by jayphizzle** [varszegimarcell/Optiplex-3020-Hackintosh-OpenCore#9]
I saw that my 3020M is capable of an add-on card to get a second DisplayPort Output.
Has someone already tried this under Big Sur or should this work out of the box?

https://www.ebay.com/itm/Dell-WFJ0V-D-Port-Card-for-Optiplex-3020M-7020M-9020M-3040M-7040M-9040M-B-3/124424536139

I would be great if I can use my two Dell 27" 2K Screens with my hackintosh.

**Comment by varszegimarcell** [comment]
Hi!

What kind of add-on card is this? Can you send me a link for it to check it out?

Sadly, with MacOS, you're never can assume that add on cards work out of the box, plug'n'play. It may work better if you would install a supported dGPU, althrough I'm not sure that there are any graphics card that would fit the 3020M.

**Comment by jayphizzle** [comment]
Hi!

you can see the card in the ebay link I posted above.
It is just a card to add an additional DisplayPort Output from a connection on the mainboard.
So the used graphic card in my case is still the HD4600.

**Comment by varszegimarcell** [comment]
As far as I see, this should work okay. The internal header is DP too, so it should work as you plug in. 

Apple writes only the DP part of the intel HD graphics drivers. To have HDMI output on Mac minis, they use a DP -> HDMI converter chip. :D just Apple...

**Comment by jayphizzle** [comment]
I made a mistake and found out my 3020M has no DP internal header, it was for the RS232 connector.
So this can be closed.
